CREATE TABLE EDITORA(
	IDEDITORA BIGSERIAL NOT NULL,
	NOMEEDITORA VARCHAR(60) NOT NULL,
	CONSTRAINT PK_EDITORA PRIMARY KEY (IDEDITORA)
);

CREATE TABLE AUTOR(
	IDAUTOR BIGSERIAL NOT NULL,
	NOMEAUTOR VARCHAR(60) NOT NULL,
	CONSTRAINT PK_AUTOR PRIMARY KEY (IDAUTOR)
);

CREATE TABLE CATEGORIA(
	IDCATEGORIA BIGSERIAL NOT NULL,
	NOMECATEGORIA VARCHAR(60) NOT NULL,
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (IDCATEGORIA)
);

CREATE TABLE LIVRO(
	IDLIVRO BIGSERIAL NOT NULL,
	TITULO VARCHAR(60) NOT NULL,
	ANOPUBLICACAO INTEGER,
	NUMEROPAGINAS INTEGER,
	NUMEROEDICAO INTEGER,
	EMPRESTADO INTEGER,
	RESUMO text,
	IDEDITORA BIGINT,
	IDCATEGORIA BIGINT,
	CONSTRAINT PK_LIVRO PRIMARY KEY (IDLIVRO),
	CONSTRAINT LIVRO_EDITORA_fkey FOREIGN KEY (IDEDITORA) REFERENCES EDITORA(IDEDITORA),
	CONSTRAINT LIVRO_CATEGORIA_fkey FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
);

CREATE TABLE LIVROAUTOR(
	IDAUTOR BIGINT,
	IDLIVRO BIGINT,
	CONSTRAINT PK_LIVROAUTOR PRIMARY KEY (IDLIVRO,IDAUTOR),
	CONSTRAINT LIVRO_AUTOR_fkey FOREIGN KEY (IDAUTOR) REFERENCES AUTOR(IDAUTOR),
	CONSTRAINT AUTOR_LIVRO_fkey FOREIGN KEY (IDLIVRO) REFERENCES LIVRO(IDLIVRO)
);

CREATE TABLE PESSOA(
	IDPESSOA BIGSERIAL NOT NULL,
	NOMEPESSOA VARCHAR(60) NOT NULL,
	CPF VARCHAR(15) not null,
	EMAIL VARCHAR(60),
	TELEFONE VARCHAR(30),
	CONSTRAINT PK_PESSOA PRIMARY KEY (IDPESSOA)
);

CREATE TABLE EMPRESTIMO(
	IDEMPRESTIMO BIGSERIAL NOT NULL,
	IDLIVRO BIGINT, 
	IDPESSOA BIGINT,
	DHEMPRESTIMO TIMESTAMP,
	DHVENCIMENTO TIMESTAMP,
	DHDEVOLUCAO TIMESTAMP,
	CONSTRAINT PK_EMPRESTIMO PRIMARY KEY (IDEMPRESTIMO),
	CONSTRAINT LIVRO_EMPRESTIMO_fkey FOREIGN KEY (IDLIVRO) REFERENCES LIVRO(IDLIVRO),
	CONSTRAINT LIVRO_PESSOA_fkey FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA)
);

CREATE TABLE USUARIO (
	IDUSUARIO BIGSERIAL NOT NULL,
	NOMEUSUARIO VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL,
	SENHA VARCHAR(10) NOT NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY (IDUSUARIO) 
);

insert into USUARIO (nomeusuario, EMAIL, SENHA)
     values ('João da Silva', 'joao@gmail.com', '123456');
     
insert into USUARIO (nomeusuario, EMAIL, SENHA)
     values ('Maria dos Santos', 'maria@gmail.com', '654321');